import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const playfair_display = Playfair_Display({ subsets: ["latin"], weight: ["400", "800"] });

export const metadata: Metadata = {
  title: "O Plano da Virada - Super Nova MKT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-KK8LV559')
        `}} />
      </head>
      <body className={`${inter.className} ${playfair_display.className}`}>
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KK8LV559"
          height="0" width="0"></iframe></noscript>
        {children}
      </body>
    </html>
  );
}
